export const casinos = [
    {
        id:1,
        name: "Sports Interaction Casino Review",
        logo: "images/sports_interaction_casino.png",
        logo2x: "images/sports_interaction_casino@2x.png",
        rating: 4.4,
        new: true,
        freeSpins: "20 Free Spins",
        bonus: "200% First deposit bonus + 250 FS",
        country: "USA",
        promoCode: "WELCOME",
        gamesAllowed: ["Slots", "Keno", "Scratch Cards", "Bingo"],
        maxCashOut: "$100",
        minDeposit: "FREE",
        popupTitle: "20 Free Spins at 21 Dukes Casino"
    },
    {
        id:2,
        name: "21 Dukes Casino Review",
        logo: "images/21_dukes_moons.png",
        logo2x: "images/21_dukes_moons2x.png",
        rating: 4.4,
        new: false,
        freeSpins: "20 Free Spins",
        bonus: "200% First deposit bonus + 250 FS",
        country: "USA",
        promoCode: "DUKES20",
        gamesAllowed: ["Poker", "Slots", "Bingo"],
        maxCashOut: "$200",
        minDeposit: "$10",
        popupTitle: "21 Dukes Casino Promo"
    },
    {
        id:3,
        name: "AC Casino Review",
        logo: "images/ac_casino.png",
        logo2x: "images/ac_casino@2x.png",
        rating: 4.4,
        new: true,
        freeSpins: "50 Free Spins",
        bonus: "200% First deposit bonus",
        country: "USA",
        promoCode: "AC50",
        gamesAllowed: ["Blackjack", "Roulette"],
        maxCashOut: "$300",
        minDeposit: "$20",
        popupTitle: "50 Free Spins at AC Casino"
    },
    {
        id:4,
        name: "All Irish Casino Review",
        logo: "images/all_irish.png",
        logo2x: "images/all_irish@2x.png",
        rating: 4.4,
        new: false,
        freeSpins: "100% First deposit bonus + 70 FS",
        bonus: "100% First deposit bonus",
        country: "USA",
        promoCode: "IRISH70",
        gamesAllowed: ["Slots", "Keno"],
        maxCashOut: "$150",
        minDeposit: "$5",
        popupTitle: "Exclusive Bonus at All Irish Casino"
    },
    {
        id:5,
        name: "All Star Games Casino Review",
        logo: "images/All Star Games Casino Review.png",
        logo2x: "images/All Star Games Casino Review@2x.png",
        rating: 4.4,
        new: true,
        freeSpins: "50 Free Spins",
        bonus: "200% First deposit bonus",
        country: "USA",
        promoCode: "AC50",
        gamesAllowed: ["Slots", "Roulette"],
        maxCashOut: "$100",
        minDeposit: "$15",
        popupTitle: "50 Free Spins at AC Casino"
    },
    {
        id:6,
        name: "All Star Slots Casino Review",
        logo: "images/All Star Slots Casino Review.png",
        logo2x: "images/All Star Slots Casino Review@2x.png",
        rating: 4.4,
        new: false,
        freeSpins: "100% First deposit bonus + 70 FS",
        bonus: "100% First deposit bonus",
        country: "USA",
        promoCode: "IRISH100",
        gamesAllowed: ["Bingo", "Keno"],
        maxCashOut: "$250",
        minDeposit: "$25",
        popupTitle: "70 FS for All Star Slots Casino Players"
    },
    {
        id:7,
        name: "Sports Interaction Casino Review",
        logo: "images/sports_interaction_casino.png",
        logo2x: "images/sports_interaction_casino@2x.png",
        rating: 4.4,
        new: false,
        freeSpins: "20 Free Spins",
        bonus: "200% First deposit bonus + 250 FS",
        country: "USA",
        promoCode: "WELCOME",
        gamesAllowed: ["Slots", "Keno", "Scratch Cards", "Bingo"],
        maxCashOut: "$100",
        minDeposit: "FREE",
        popupTitle: "20 Free Spins at Sports Interaction Casino"
    },
    {
        id:8,
        name: "VIP Stakes Casino Review",
        logo: "images/VIP Stakes.png",
        logo2x: "images/VIP Stakes@2x.png",
        rating: 4.4,
        new: false,
        freeSpins: "100% First deposit bonus + 70 FS",
        bonus: "100% First deposit bonus",
        country: "USA",
        promoCode: "IRISH70",
        gamesAllowed: ["Poker", "Slots", "Keno"],
        maxCashOut: "$150",
        minDeposit: "$10",
        popupTitle: "VIP Stakes Casino Exclusive Offer"
    },
    {
        id:9,
        name: "Jackpot Capital Casino Review",
        logo: "images/Jacpot Capital.png",
        logo2x: "images/Jacpot Capital@2x.png",
        rating: 4.4,
        new: false,
        freeSpins: "100% First deposit bonus + 70 FS",
        bonus: "100% First deposit bonus",
        country: "USA",
        promoCode: "IRISH100",
        gamesAllowed: ["Bingo", "Roulette"],
        maxCashOut: "$200",
        minDeposit: "$20",
        popupTitle: "Special Bonus at Jackpot Capital Casino"
    }
];